#!/usr/bin/env bash
# Install an configure HAProxy load balancer

# Install HAProxy version for Ubuntu 20.04LTS
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get install -y haproxy=2.8.\*

# Configure HAProxy
echo "frontend albert-frontend
	bind *:80
	mode http
	default_backend albert-backend
backend albert-backend
	balance roundrobin
	server web-01 100.26.234.115:80 check
	server web-02 52.91.132.168:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
# Allow HAProxy management by init script
# sudo systemctl enable haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null

# Restart HAProxy
sudo service haproxy restart
