#!/usr/bin/env bash
# I have only two weaknesses

pid=$$
sudo touch /var/run/myscript.pid
sudo chmod o+rw /var/run/myscript.pid
echo "$pid" > /var/run/myscript.pid
trap 'sudo rm /var/run/myscript.pid && kill '$pid' ' SIGQUIT
trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!" SIGINT
while true; do
	echo To infinity and beyond
	sleep 2
done
