#!/usr/bin/env bash
# Run nginx as nginx
sudo sed -i '/^#user www-data/i user nginx;' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80/listen \[::\]:8080/' /etc/nginx/sites-available/default
sudo chmod 444 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
